# Generated by Django 4.1.4 on 2023-02-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=30)),
                ('codigo_mascota', models.IntegerField()),
                ('email_dueño', models.EmailField(max_length=254)),
                ('zona', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('zona', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.IntegerField()),
                ('nombre_reserva', models.CharField(max_length=30)),
                ('fecha_reserva', models.DateField()),
                ('confirmacion', models.BooleanField()),
            ],
        ),
    ]
