# Generated by Django 4.1.4 on 2023-02-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MokaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Mascotas',
        ),
    ]
